# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded faq 1.2 [list tclPkgSetup $dir faq 1.2 {{faq.tcl source {FAQ FAQ_H1 FAQ_H2 FAQgen FAQgenQ FAQgenSec FAQinit FAQlink FAQlinkResolve FAQregQuote FAQsection}}}]
package ifneeded form 1.0 [list tclPkgSetup $dir form 1.0 {{form.tcl source {::form::checkbox ::form::checkset ::form::checkvalue ::form::classbox ::form::classboxEnd ::form::classboxStart ::form::data ::form::empty ::form::getFormInfo ::form::incrNumber ::form::line ::form::radioset ::form::radiovalue ::form::select ::form::selectplain ::form::startNumber ::form::submit ::form::text ::form::value}}}]
package ifneeded htmlutils 1.0 [list tclPkgSetup $dir htmlutils 1.0 {{htmlutils.tcl source {/code Author Body Capitalize CloseTag Code Date DynamicOnly Email End Font FtpSize GetUserAgent Head InsertFile InsertTemplate Keywords LastChange LastModified Link Mailto MinorMenu Noop OpenTag Path PersonP Raw RelativeUrl Row ShowArray ShowQuery Space TclPower Title UserAgentMatch VSpace code}}}]
package ifneeded sunscript 1.2 [list tclPkgSetup $dir sunscript 1.2 {{sunscript.tcl source {SunscriptBody SunscriptEnd SunscriptH1 SunscriptH2 SunscriptHead SunscriptHeading SunscriptItem SunscriptMenu SunscriptSpacer _SunscriptFooter _SunscriptMenuEnd}}}]
package ifneeded survey 1.0 [list tclPkgSetup $dir survey 1.0 {{ss_survey.tcl source {DataChoice FormAction Survey/download Survey/showfiles}}}]
