# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -direct" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded admin 1.0 [list source [file join $dir admin.tcl]]
package ifneeded auth 1.0 [list source [file join $dir auth.tcl]]
package ifneeded base64 1.0 [list source [file join $dir base64.tcl]]
package ifneeded cgi 1.1 [list source [file join $dir cgi.tcl]]
package ifneeded counter 1.0 [list source [file join $dir counter.tcl]]
package ifneeded debug 1.0 [list source [file join $dir debug.tcl]]
package ifneeded demo 1.0 [list source [file join $dir demo.tcl]]
package ifneeded direct 1.0 [list source [file join $dir direct.tcl]]
package ifneeded dirlist 1.0 [list source [file join $dir dirlist.tcl]]
package ifneeded doc 1.1 [list source [file join $dir doc.tcl]]
package ifneeded html 1.0 [list source [file join $dir html.tcl]]
package ifneeded httpd 1.1 [list source [file join $dir httpd.tcl]]\n[list source [file join $dir version.tcl]]
package ifneeded include 1.0 [list source [file join $dir include.tcl]]
package ifneeded ismaptcl 1.0 [list source [file join $dir imagemap.tcl]]\n[list source [file join $dir maptcl.tcl]]
package ifneeded ismaptk 1.0 [list source [file join $dir maptk.tcl]]
package ifneeded log 1.0 [list source [file join $dir log.tcl]]
package ifneeded mail 1.0 [list source [file join $dir mail.tcl]]
package ifneeded mtype 1.0 [list source [file join $dir mtype.tcl]]
package ifneeded opentrace 1.0 [list source [file join $dir open.tcl]]
package ifneeded safecgio 1.0 [list source [file join $dir safecgio.tcl]]
package ifneeded session 1.0 [list source [file join $dir session.tcl]]
package ifneeded snmp 1.0 [list source [file join $dir discover.tcl]]\n[list source [file join $dir snmp.tcl]]\n[list source [file join $dir telnet.tcl]]
package ifneeded srvui 1.0 [list source [file join $dir srvui.tcl]]
package ifneeded status 1.1 [list source [file join $dir status.tcl]]
package ifneeded stdin 1.1 [list source [file join $dir stdin.tcl]]
package ifneeded threadmgr 1.0 [list source [file join $dir thread.tcl]]
package ifneeded url 2.0 [list source [file join $dir url.tcl]]
package ifneeded utils 1.0 [list source [file join $dir utils.tcl]]
