#!/bin/sh
#
# Create a super distribution of TclHttpd, Tcl, Tcllib, and Thread

HTTPD_VERSION=3.5.0
HTTPD_TAG=tclhttpd-3-5-rel-0
HTTPD_TAG=HEAD
WIN_VERSION=350
DISTDIR=/usr10/home/welch/dist
SUPER_DIR=${DISTDIR}/tclhttpd${HTTPD_VERSION}-dist

TCL_VERSION=8.4.5
TCL_DIST=${DISTDIR}/tcl${TCL_VERSION}-src.tar.gz

TCLLIB_VERSION=1.4
TCLLIB_DIST=${DISTDIR}/tcllib-${TCLLIB_VERSION}.tar.gz

THREAD_VERSION=2.6
THREAD_WIN_VERSION=26
THREAD_TAG=thread-2-6
THREAD_TAG=HEAD

SCRATCH=/usr10/home/welch/scratch
mkdir ${SCRATCH}
cd ${SCRATCH}

rm -rf ${SCRATCH}/tclhttpd${HTTPD_VERSION}
cvs -d welch@cvs.sourceforge.net:/cvsroot/tclhttpd checkout -r ${HTTPD_TAG} tclhttpd 
(cd tclhttpd ; cvs -d welch@cvs.sourceforge.net:/cvsroot/tclpro checkout config)
mv tclhttpd tclhttpd${HTTPD_VERSION}
chmod -R a+r tclhttpd${HTTPD_VERSION}
chmod a+x tclhttpd${HTTPD_VERSION}/bin/httpd.tcl
chmod a-x tclhttpd${HTTPD_VERSION}/bin/httpdthread.tcl
chmod a+x tclhttpd${HTTPD_VERSION}/htdocs/cgi-bin/junk*
chmod a+x tclhttpd${HTTPD_VERSION}/htdocs/cgi-bin/env
find tclhttpd${HTTPD_VERSION}/htdocs -name "*.cgi" -exec chmod a+x {} \;
cp tclhttpd${HTTPD_VERSION}/license.terms tclhttpd${HTTPD_VERSION}/htdocs
mkdir tclhttpd${HTTPD_VERSION}/htdocs/links
cp tclhttpd${HTTPD_VERSION}/README tclhttpd${HTTPD_VERSION}/htdocs/links/README.txt
cp tclhttpd${HTTPD_VERSION}/certs/README.ssl tclhttpd${HTTPD_VERSION}/htdocs/links/README.ssl.txt
cp tclhttpd${HTTPD_VERSION}/WHATSNEW tclhttpd${HTTPD_VERSION}/htdocs/links/WHATSNEW.txt
cp tclhttpd${HTTPD_VERSION}/INSTALL tclhttpd${HTTPD_VERSION}/htdocs/links/INSTALL.txt

rm -rf ${SCRATCH}/thread${THREAD_VERSION}
cvs -d welch@cvs.sourceforge.net:/cvsroot/tcl checkout -r ${THREAD_TAG} thread
(cd thread ; cvs -d welch@cvs.sourceforge.net:/cvsroot/tclpro checkout config)
mv thread thread${THREAD_VERSION}
chmod -R a+r thread${THREAD_VERSION}

cd tclhttpd${HTTPD_VERSION}
autoconf
cd ..

cd thread${THREAD_VERSION}
autoconf
cd ..

cd tclhttpd${HTTPD_VERSION}/DIST_build

#sh ../configure --enable-gcc --with-tcl=/home/welch/cvs/tcl8.3/unix/solaris \
#	--prefix=/usr/local 

SRCDIR=..

rm -rf ${SUPER_DIR}
mkdir ${SUPER_DIR}
mkdir ${SUPER_DIR}/tclhttpd${HTTPD_VERSION}
tclsh ${SRCDIR}/bin/CopyDist ${SRCDIR} ${SUPER_DIR}/tclhttpd${HTTPD_VERSION}

mkdir ${SUPER_DIR}/thread${THREAD_VERSION}
tclsh ${SRCDIR}/bin/CopyDist ${SRCDIR}/../thread${THREAD_VERSION} ${SUPER_DIR}/thread${THREAD_VERSION}
gunzip < ${TCL_DIST} | (cd ${SUPER_DIR} ; tar xf -)
gunzip < ${TCLLIB_DIST} | (cd ${SUPER_DIR} ; tar xf -)

mkdir ${SUPER_DIR}/build
########cp CONFIG MAKE ${SUPER_DIR}/build

cp README ${SUPER_DIR}
sed -e s/@HTTPD_VERSION@/$HTTPD_VERSION/ \
    -e s/@TCL_VERSION@/$TCL_VERSION/ \
    -e s/@TCLLIB_VERSION@/$TCLLIB_VERSION/ \
    -e s/@THREAD_VERSION@/$THREAD_VERSION/ \
        < Makefile.boot > ${SUPER_DIR}/Makefile

# Unbundled packages

(cd ${DISTDIR}/tclhttpd${HTTPD_VERSION}-dist ; tar cf - ./tclhttpd${HTTPD_VERSION} | gzip > ${DISTDIR}/tclhttpd${HTTPD_VERSION}.tar.gz)
(cd ${DISTDIR}/tclhttpd${HTTPD_VERSION}-dist ; zip -9 -r -o  ${DISTDIR}/tclhttpd${WIN_VERSION}.zip  tclhttpd${HTTPD_VERSION})

(cd ${DISTDIR}/tclhttpd${HTTPD_VERSION}-dist ;tar cf - ./thread${THREAD_VERSION} | gzip > ${DISTDIR}/thread${THREAD_VERSION}.tar.gz)
(cd ${DISTDIR}/tclhttpd${HTTPD_VERSION}-dist ;zip -9 -r -o  ${DISTDIR}/thread${THREAD_WIN_VERSION}.zip thread${THREAD_VERSION})

# Bundled packages

(cd ${DISTDIR}; tar cf - ./tclhttpd${HTTPD_VERSION}-dist | gzip > tclhttpd${HTTPD_VERSION}-dist.tar.gz)
(cd ${DISTDIR} ; zip -9 -r -o  tclhttpd${WIN_VERSION}dist.zip  tclhttpd${HTTPD_VERSION}-dist)
